---
- name: Make sure config directory exists
  file:
    path: "{{ php5_fpm_nginx_config_dir }}"
    state: directory
- name: Copy PHP config for nginx
  template:
    src: php.conf
    dest: "{{ php5_fpm_nginx_config_dir }}/php.conf"
  tags: [package,php5-fpm,nginx]
