---
- name: Add nginx PPA
  apt_repository: repo='ppa:nginx/stable'
  tags: [packages,nginx]

- name: Install nginx
  apt: name=nginx state=present
  tags: [packages,nginx]

- name: Configure nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: reload nginx
  tags: [packages,nginx]

- name: Add mime types
  copy:
    src: mime.types
    dest: /etc/nginx/mime.types
  notify: reload nginx
  tags: [packages,nginx]
