---

- name: Install nginx
  apt: name=nginx state=present update_cache=yes
  tags: [packages,nginx]

- name: Configure nginx
  copy:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx
  tags: [packages,nginx]

- name: Add mime types
  copy:
    src: mime.types.j2
    dest: /etc/nginx/mime.types
  notify: reload nginx
  tags: [packages,nginx]
