---

- name: install uwsgi
  pip: name=uwsgi
  tags: [packages,uwsgi]

- name: install init script
  template: src=init.j2
            dest=/etc/init.d/uwsgi
            owner=root
            group=root
            mode=0755
  tags: [uwsgi,uwsgi-init]

- name: install defaults
  template: src=defaults.j2
            dest=/etc/default/uwsgi
            owner=root
            group=root
            mode=0644
  tags: [uwsgi,uwsgi-init]

- name: create log directory
  file: path={{ uwsgi_log_dir }}
        owner=root
        group=root
        mode=0755
        state=directory
  tags: [uwsgi]

- name: create config directory
  file: path={{ uwsgi_config_dir }}
        owner=root
        group=root
        mode=0755
        state=directory
  tags: [uwsgi]

- name: start at boot
  service: name=uwsgi
           enabled=yes
  tags: [uwsgi,uwsgi-init]
