---

- name: install ant
  apt: pkg=ant
  tags: [packages,dfbnc-dependencies,dfbnc]

- include: ../../shared/deploy-git-project.yml
  vars:
    repo: https://github.com/ShaneMcC/DFBnc.git
    user: "{{ dfbnc_user }}"
    dest: "{{ dfbnc_dir }}/src"
    version: "{{ dfbnc_version }}"
  tags: [dfbnc]

- name: build dfbnc
  sudo: true
  sudo_user: "{{ dfbnc_user }}"
  environment:
    LANG: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  command: chdir={{ dfbnc_dir }}/src
           ant jar
  when: git_clone.changed
  tags: [dfbnc-setup,dfbnc]

- name: create config directory
  sudo: true
  sudo_user: "{{ dfbnc_user }}"
  file: owner={{ dfbnc_user }}
        path={{ dfbnc_dir }}/DFBnc
        state=directory
  tags: [dfbnc-setup,dfbnc-config,dfbnc]

- include: ../../shared/generate-password.yml
  tags: [dfbnc-setup,dfbnc-config,dfbnc-ssl,dfbnc]

- name: create keystore
  sudo: true
  sudo_user: "{{ dfbnc_user }}"
  command: chdir={{ dfbnc_dir }}
           creates={{ dfbnc_dir }}/keystore.ks
           keytool -genkey -validity 365 -keystore "keystore.ks" -storepass "{{ random_password.stdout }}"
                   -keypass "{{ random_password.stdout }}" -alias "default"
                   -dname "{{ dfbnc_ssl_dn }}"
  register: dfbnc_keystore_create
  tags: [dfbnc-setup,dfbnc-config,dfbnc-ssl,dfbnc]

- name: chmod keystore
  sudo: true
  sudo_user: "{{ dfbnc_user }}"
  file: mode=0600
        path={{ dfbnc_dir }}/keystore.ks
  tags: [dfbnc-setup,dfbnc-config,dfbnc-ssl,dfbnc]

- name: copy config
  sudo: true
  sudo_user: "{{ dfbnc_user }}"
  template: src=dfbnc.conf.j2
            dest={{ dfbnc_dir }}/DFBnc/DFBnc.conf
            owner={{ dfbnc_user }}
            mode=0600
  when: dfbnc_keystore_create.changed
  tags: [dfbnc-setup,dfbnc-config,dfbnc]
