---

- name: Create sentry user
  user: name={{ sentry_user }}

- name: Create virtual environment
  sudo: true
  sudo_user: "{{ sentry_user }}"
  command: virtualenv "{{ sentry_dir }}"
           creates={{ sentry_dir }}/bin/activate

- name: Copy virtual env wrapper script
  sudo: true
  sudo_user: "{{ sentry_user }}"
  template: src=venv_exec.j2
            dest={{ sentry_dir }}/exec
            mode=755

- name: Install sentry
  sudo: true
  sudo_user: "{{ sentry_user }}"
  command: "{{ sentry_dir }}/exec easy_install -UZ sentry[mysql]
           creates={{ sentry_dir }}/bin/sentry"

- name: Create sentry configuration dir
  sudo: true
  sudo_user: "{{ sentry_user }}"
  file: path={{ sentry_dir }}/etc
        state=directory

- name: Copy sentry configuration
  sudo: true
  sudo_user: "{{ sentry_user }}"
  template: src=sentry.conf.j2
            dest={{ sentry_dir }}/etc/sentry.conf

- name: Create MySQL database
  mysql_db: name={{ sentry_db_name }}
  register: sentry_db_create

- include: ../../shared/generate-password.yml
  when: sentry_db_create.changed

- name: Create MySQL user
  mysql_user: name={{ sentry_db_user }}}
              password={{ random_password.stdout }}
              priv={{ sentry_db_name }}.*:ALL
  when: sentry_db_create.changed

- name: Store MySQL user password
  copy: dest={{ sentry_dir }}/etc/mysql.pass
        content="{{ random_password.stdout }}"
        owner={{ sentry_user }}
        mode=600
  when: sentry_db_create.changed
